### ISSUE TITLE
Packageify should support non-root paths

### ISSUE THREAD

**Issue by pose** [auth0/packageify#2]
I've the following project structure:

```
|
|--- package.json
|--- index.js
|---lib
     |--- hello.js
```

Contents of `package.json`:

```json
{
  "name": "bla",
  "version": "0.0.1",
  "foo": {
    "bar": true
  }
  ...
}
```

And `lib/hello.js` looks like this:

```js
var propery = require('package.foo.bar');
...
```

**What should happen?**
It should compile and `property` should be equal `true`.

**What happens instead?**
A message is displayed that compilation failed.

**Comment by NickTomlin** [comment]
This could be easily accomplished by using [`lodash.get`](https://lodash.com/docs#get). I'd be happy to submit a PR for this.

**Comment by jfromaniello** [comment]
Yes! Go ahead

**Comment by NickTomlin** [comment]
Done! :)
